version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: multi-blockchain-postgres
    environment:
      POSTGRES_USER: blockchain_user
      POSTGRES_PASSWORD: blockchain_password
      POSTGRES_DB: multi_blockchain_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockchain_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: multi-blockchain-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: multi-blockchain-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@blockchain.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  pgadmin_data: