[build]
  publish = "public"
  command = "mkdir -p public && cp *.html public/ && echo 'Static files copied'"

[functions]
  directory = "netlify/functions"

# Disable all automatic framework detection
[build.environment]
  NETLIFY_SKIP_FRAMEWORK_DETECTION = "true"
  NODE_VERSION = "20"

[[redirects]]
  from = "/"
  to = "/coingecko-ui.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin-panel.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-simple"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"